-- MySQL Script generated by MySQL Workbench
-- Sun 08 Nov 2015 03:09:37 PM COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisnotdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisnotdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisnotdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sisnotdb` ;

-- -----------------------------------------------------
-- Table `sisnotdb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisnotdb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `sisnotdb`.`Administrador` (
  `idAdministrador` BIGINT(100) NOT NULL COMMENT '',
  `nombreCompleto` VARCHAR(45) NOT NULL COMMENT '',
  `correoElectronico` VARCHAR(45) NOT NULL COMMENT '',
  `contrasena` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idAdministrador`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisnotdb`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisnotdb`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `sisnotdb`.`Alumno` (
  `idAlumno` BIGINT(100) NOT NULL COMMENT '',
  `apellidos` VARCHAR(45) NOT NULL COMMENT '',
  `nombres` VARCHAR(45) NOT NULL COMMENT '',
  `edad` TINYINT(5) NOT NULL COMMENT '',
  `correoElectronico` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `celular` VARCHAR(45) NULL COMMENT '',
  `contrasena` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idAlumno`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisnotdb`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisnotdb`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `sisnotdb`.`Profesor` (
  `idProfesor` BIGINT(100) NOT NULL COMMENT '',
  `nombres` VARCHAR(45) NOT NULL COMMENT '',
  `apellidos` VARCHAR(45) NOT NULL COMMENT '',
  `edad` TINYINT(5) NOT NULL COMMENT '',
  `correoElectronico` VARCHAR(45) NOT NULL COMMENT '',
  `contrasena` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idProfesor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisnotdb`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisnotdb`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `sisnotdb`.`Asignatura` (
  `idAsignatura` BIGINT(100) NOT NULL COMMENT '',
  `idProfesor` BIGINT(100) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idAsignatura`)  COMMENT '',
  INDEX `fk_Asignatura_Profesor_idx` (`idProfesor` ASC)  COMMENT '',
  CONSTRAINT `fk_Asignatura_Profesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `sisnotdb`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisnotdb`.`Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisnotdb`.`Nota` ;

CREATE TABLE IF NOT EXISTS `sisnotdb`.`Nota` (
  `idNota` BIGINT(100) NOT NULL COMMENT '',
  `idAsignatura` BIGINT(100) NOT NULL COMMENT '',
  `idProfesor` BIGINT(100) NOT NULL COMMENT '',
  `idAlumno` BIGINT(100) NOT NULL COMMENT '',
  `nota` DECIMAL NOT NULL COMMENT '',
  PRIMARY KEY (`idNota`)  COMMENT '',
  INDEX `fk_Nota_Asignatura_idx` (`idAsignatura` ASC)  COMMENT '',
  INDEX `fk_Nota_Profesor_idx` (`idProfesor` ASC)  COMMENT '',
  INDEX `fk_Nota_Alumno_idx` (`idAlumno` ASC)  COMMENT '',
  CONSTRAINT `fk_Nota_Asignatura`
    FOREIGN KEY (`idAsignatura`)
    REFERENCES `sisnotdb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota_Profesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `sisnotdb`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota_Alumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `sisnotdb`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
